<?php

return [
  'application' => [
    'theme' => '{{cookiecutter.slug}}',
    'general' => [
      // 'site-title' => '{{cookiecutter.theme_name}}',
      // 'tagline' => 'Otro sitio de WordPress',
      // 'wp-address' => '{{cookiecutter.theme_uri}}/wp',
      // 'site-address' => '{{cookiecutter.theme_uri}}',
      'admin-email' => 'servicios+{{cookiecutter.project}}@crea.me',
      'membership' => false,
      'default-role' => 'subscriber',
      'language' => 'es_ES',
      'timezone' => 'Europe/Madrid',
      // 'date-format' => 'j \\d\\e F \\d\\e Y',
      'time-format' => 'G:i',
      'week-starts' => 'Monday',
    ],
    'writing' => [
      'emoji' => false,
      'default-category' => 1,
      'default-post-format' => 'standard',
      'post-via-email.server' => 'mail.example.com',
      'post-via-email.login' => 'login@example.com',
      'post-via-email.pass' => 'password',
      'post-via-email.port' => 110,
      'post-via-email.default-category' => 1,
      'update-services' => '',
    ],
    // 'reading' => [
    //   'front-page' => 'posts',
    //   'front-page.page' => 0,
    //   'front-page.posts' => 0,
    //   'posts-per-page' => 10,
    //   'posts-per-rss' => 10,
    //   'rss-excerpt' => 'full',
    //   'discourage-search' => false,
    // ],
    'discussion' => [
      'post.ping-flag' => true,
      'post.ping-status' => true,
      'post.comments' => true,
      'comments.name-email' => true,
      'comments.registration' => true,
      'comments.close' => true,
      'comments.close.days' => 30,
      'comments.cookies' => true,
      'comments.thread' => true,
      'comments.thread.depth' => 5,
      'comments.pages' => true,
      'comments.pages.per-page' => 50,
      'comments.pages.default' => 'newest',
      'comments.order' => 'asc',
      'emails.comment' => true,
      'emails.moderation' => true,
      'moderation.approve-manual' => true,
      'moderation.approve-previous' => true,
      'moderation.queue-links' => 0,
      'moderation.queue-keys' => '',
      'moderation.disallowed-keys' => '',
      'avatars' => false,
      'avatars.rating' => 'G',
      'avatars.default' => 'mystery',
    ],
    'media' => [
      'sizes.thumbnail.width' => 150,
      'sizes.thumbnail.height' => 150,
      'sizes.thumbnail.crop' => true,
      'sizes.medium.width' => 300,
      'sizes.medium.height' => 300,
      'sizes.large.width' => 1024,
      'sizes.large.height' => 1024,
      'uploads.organize' => true,
      'mimes.svg' => true, // Allow upload SVGs.
    ],
    'permalinks' => [
      'structure' => '/%postname%/',
      'category-base' => 'categoria',
      'tag-base' => 'etiqueta',
    ],
  ],
  'wp-admin' => [
    'all' => [
      'common.adminbar.wp' => true,
      'common.adminbar.site.themes' => true,
      'common.adminbar.user.howdy' => true,
      'common.adminbar.user.profile' => true,
      'dashboard.home.welcome' => true,
      'dashboard.home.news' => true,
      'posts.item.trackbacks' => true,
      'posts.item.custom-fields' => true,
      'posts.item.format' => true,
      'pages.item.author' => true,
      'pages.item.custom-fields' => true,
      'pages.item.discussion' => true,
    ],
    'all-not-administrator' => [
      'common.adminbar.updates' => true,
    ],
  ],
];